version: '3.9'
services:

  frontend-nextjs:
    container_name: FRONTEND-NEXTJS
    restart: unless-stopped
    build:
      context: .
      dockerfile: .docker/Dockerfile
    volumes:
        - ./app:/app
        - /app/node_modules
        - /app/.next
    ports:
      - 3000:3000