import type { Metadata } from "next";
import  AuthProvider  from "./_context/AuthProvider"
import "./globals.css";
import { getServerSession } from "next-auth";
import { options } from "./api/auth/[...nextauth]/options";
import { redirect } from "next/navigation";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await getServerSession(options);
  return (
    <html lang="en">
      <body>
        <AuthProvider>
          <div className="h-screen w-screen flex flex-col">
            <div className=" bg-gray-800 h-[40px] w-full flex justify-end gap-2 p-2 items-center">
              {session? session.user.email:""}
              {session && session.user.role === "KITCHEN"?
                <div className="flex gap-1">
                  <a className="bg-gray-700 rounded-md p-1" href="/signage">Signage</a>
                  <a className="bg-gray-700 rounded-md p-1" href="/pedidos">Pedidos</a>
                </div>
                :
                <></>}
              <a className="bg-gray-700 rounded-md p-1" href="/menu">Menu</a>
              {session?
                <a className="bg-gray-700 rounded-md p-1" href="/api/auth/signout?callbackUrl=/menu">SignOut</a>
                :
                <a className="bg-gray-700 rounded-md p-1" href="/api/auth/signin?callbackUrl=/menu">SignIn</a>}
            </div>
            <div className="w-full flex-grow text-black">
              {children}
            </div>
          </div>
        </AuthProvider>
      </body>
    </html>
  );
}
